// Parametric OEM 3-Rib Shaft & Rocker Mechanism for Kia Socket Enclosure
// Generated by build_shaft.py

$fn = 64;

// Global Parameters (mm)
total_axle_len = 11.5;
hub_w = 7.5;
pin_d = 2.8;
pin_len = 2.00;
hub_d = 4.2;

plunger_reach_below_z = 6.5;
plunger_w = 4.4;
plunger_y_c = 11.4;

cam_w = 2.7;
cam_x_c = 7.05;

module oem_shaft_rocker() {
    // Left Pivot Pin
    translate([-(total_axle_len/2 - pin_len/2), 0, 0])
        rotate([0, 90, 0])
            cylinder(r = pin_d/2, h = pin_len, center = true);
            
    // Right Pivot Pin
    translate([(total_axle_len/2 - pin_len/2), 0, 0])
        rotate([0, 90, 0])
            cylinder(r = pin_d/2, h = pin_len, center = true);
            
    // Central Hub Barrel
    rotate([0, 90, 0])
        cylinder(r = hub_d/2, h = hub_w, center = true);
}

oem_shaft_rocker();
