// Parametric OEM 3-Prong Shaft & Rocker Mechanism for Kia Socket Enclosure
// Generated by build_shaft.py

$fn = 64;

// Global Parameters (mm)
total_axle_len = 11.5;
hub_w = 7.6;
pin_d = 1.9;
pin_len = 1.95;
hub_d = 3.3;

plunger_reach_below_z = 6.5;
prong_side_w = 0.85;
prong_center_w = 2.0;

cam_w = 2.6;
cam_x_c = 6.8;

module oem_shaft_rocker() {
    // Left Pivot Pin
    translate([-(total_axle_len/2 - pin_len/2), 0, 0])
        rotate([0, 90, 0])
            cylinder(r = pin_d/2, h = pin_len, center = true);
            
    // Right Pivot Pin
    translate([(total_axle_len/2 - pin_len/2), 0, 0])
        rotate([0, 90, 0])
            cylinder(r = pin_d/2, h = pin_len, center = true);
            
    // Central Hub Barrel
    rotate([0, 90, 0])
        cylinder(r = hub_d/2, h = hub_w, center = true);
}

oem_shaft_rocker();
