// Kia EV6 Outlet Interlock - Anti-Spreading Tower Prong Clamp (Option 2)
// Generated by build_clamp.py

$fn = 64;

// Global parameters
z_top = 14.09;
roof_thick = 1.6;
wall_thick = 1.4;
side_thick = 1.6;
pin_clearance_r = 1.85;
y_axle = 9.279;
z_axle = 12.59;

module tower_clamp_left() {
    // Left Tower Clamp with outer side retention ears and zero pin contact
    difference() {
        union() {
            // Main U-saddle
            translate([3.90, 0, 0])
                linear_extrude(height = 1.475)
                    polygon(points = [
                        [5.314, 11.20], [5.360, 14.59], [5.760, 14.99],
                        [13.370, 14.99], [13.370, 14.59], [13.498, 11.20],
                        [12.698, 11.20], [12.348, 11.55], [12.220, 14.09],
                        [11.208, 14.09], [10.908, 14.17], [10.758, 14.02],
                        [7.800, 14.02], [7.650, 14.17], [7.350, 14.09],
                        [6.510, 14.09], [6.464, 11.55], [6.114, 11.20]
                    ]);
            // Outer side wall
            translate([3.00, 0, 0])
                linear_extrude(height = 0.90)
                    difference() {
                        polygon(points = [
                            [5.314, 12.10], [5.360, 14.59], [5.760, 14.99],
                            [13.370, 14.99], [13.370, 14.59], [13.498, 12.10],
                            [10.75, 12.10], [7.80, 12.10]
                        ]);
                        // Pin clearance arch
                        translate([y_axle, z_axle])
                            circle(r = pin_clearance_r);
                    }
        }
    }
}

tower_clamp_left();
